// Neutral visitor copy. Cultural descriptions and resource metadata come from the API.
export const copy = {
  media: {
    video: 'Video',
    audio: 'Audio',
    duration: 'Duración',
    noAudioTranscript: 'La transcripción de este audio no está disponible.',
    noVideoCaptions: 'Este video no tiene subtítulos disponibles.',
    videoUnsupported: 'Tu navegador no puede reproducir este video.',
    audioUnsupported: 'Tu navegador no puede reproducir este audio.',
    spanish: 'Español',
    externalTab: '(se abre en otra pestaña)',
    lastCorrection: 'Última corrección',
    author: 'por',
    imageLabel: (title: string) => 'Imagen de ' + title,
    videoLabel: (title: string) => 'Video de ' + title,
    audioLabel: (title: string, narration: boolean) => (narration ? 'Narración de ' : 'Audio de ') + title,
    seconds: (count: number) => `${count} ${count === 1 ? 'segundo' : 'segundos'}`,
    people: {
      kamentsa: 'Pueblo Kamëntsá',
      inga: 'Pueblo Inga',
      shared: 'Participación compartida',
    } as Record<string, string>,
  },
  site: {
    name: 'Musiyo Bëtsknaté',
    subtitle: 'Museo virtual del Carnaval del Perdón',
    home: 'Inicio',
    catalog: 'Catálogo',
    tour: 'Recorrido',
    about: 'Acerca',
    privacy: 'Privacidad',
    validators: 'Validadores',
    skip: 'Saltar al contenido',
    navigation: 'Navegación principal',
    information: 'Información del museo',
  },
  common: {
    retry: 'Reintentar',
    loading: 'Cargando contenido…',
    openDetail: 'Ver ficha',
    backCatalog: '← Volver al catálogo',
    model: 'Modelo 3D',
    narration: 'Narración',
    noPhoto: 'Fotografía no disponible',
    textRecord: 'Ficha de lectura',
    inspect: 'Examinar en 3D',
    closeModel: 'Cerrar modelo 3D',
    noWebModel: 'No hay una variante de este modelo disponible para la Web.',
    credit: 'Crédito',
    provenance: 'Procedencia',
  },
  home: {
    eyebrow: 'Museo virtual · una visita a tu ritmo',
    title: 'Musiyo',
    titleAccent: 'Bëtsknaté',
    intro: 'Explora el museo, consulta sus fichas y examina las piezas disponibles. Elige por dónde comenzar y vuelve a cada sala a tu ritmo.',
    enter: 'Explorar el museo',
    catalog: 'Explorar catálogo',
    note: 'Las fuentes y restricciones de uso acompañan a cada ficha.',
    exhibition: 'Exposición / máscaras',
    exhibitionTitle: 'Una mirada a las piezas',
    exhibitionIntro: 'Abre una ficha para conocer su contexto y examinar su modelo 3D, cuando esté disponible.',
    allMasks: 'Ver la exposición',
    unavailable: 'No hay piezas disponibles en esta exposición.',
    featured: 'Pieza del catálogo',
    showcaseNote: 'El modelo se carga cuando decides examinarlo.',
    ways: 'Formas de explorar',
    waysTitle: 'El museo, a tu manera',
    reading: 'Fichas y fuentes',
    readingIntro: 'Consulta los textos, las referencias y los créditos de cada elemento.',
    visitIntro: 'Recorre las salas libremente desde un computador. También puedes elegir la visita en texto.',
    textTour: 'Recorrido en texto',
    visitTitle: 'Entra, detente, vuelve',
    visitNote: 'La ruta sugerida dura unos 30 minutos. Tú eliges el camino.',
    about: 'Conocer el proyecto',
  },
  catalog: {
    eyebrow: 'Archivo / catálogo',
    title: 'Catálogo cultural',
    intro: 'Busca una pieza, consulta su ficha y descubre dónde aparece en el museo.',
    search: 'Buscar en el catálogo',
    placeholder: 'Nombre, técnica, material o término…',
    submit: 'Buscar',
    filters: 'Filtros',
    category: 'Categoría',
    collection: 'Colección',
    allCategories: 'Todas las categorías',
    allCollections: 'Todas las colecciones',
    missingCategory: 'Categoría no disponible',
    missingCollection: 'Colección no disponible',
    clear: 'Limpiar filtros',
    filterError: 'No fue posible cargar los filtros.',
    searching: 'Buscando…',
    emptyTitle: 'No hay elementos que coincidan',
    emptyIntro: 'Prueba otra búsqueda o limpia los filtros.',
    firstPage: 'Volver a la primera página',
    previous: 'Anterior',
    next: 'Siguiente',
    pagination: 'Páginas del catálogo',
    note: 'Cada pieza se presenta con su contexto, fuentes y restricciones de uso. Los recursos disponibles se indican en su ficha.',
    result: (count: number) => `${count} ${count === 1 ? 'resultado' : 'resultados'}`,
    page: (value: number,
    total: number) => `Página ${value} de ${total}`,
  },
  detail: {
    eyebrow: 'Archivo / ficha',
    loading: 'Cargando ficha…',
    correct: 'Corregir ficha',
    community: 'Comunidad',
    category: 'Categoría',
    collections: 'Colecciones',
    technique: 'Técnica',
    materials: 'Materiales',
    sources: 'Fuentes',
    credits: 'Créditos',
    restrictions: 'Restricciones de uso',
    images: 'Imágenes',
    multimedia: 'Narraciones y multimedia',
    transcription: 'Leer transcripción',
    noResources: 'Esta ficha se puede consultar en texto. No tiene recursos visuales disponibles.',
    context: 'Contexto',
    source: 'Fuente',
    accordingTo: 'Según ',
    openTour: 'Ver en el recorrido 3D',
    openTextTour: 'Ver las salas en texto',
    viewHelp: 'Carga el modelo para rotarlo, acercarte y restablecer la vista. Puedes seguir leyendo la ficha.',
    documented: 'Lo documentado',
    testimony: 'Testimonios',
    interpretation: 'Interpretaciones',
  },
  tour: {
    eyebrow: 'Experiencia / recorrido',
    title: 'Recorrido virtual',
    intro: 'Explora libremente las salas. La ruta sugerida dura unos 30 minutos; puedes detenerte en cada pieza y elegir tu propio camino.',
    text: 'Explorar el recorrido en texto',
    catalog: 'Volver al catálogo',
    rooms: 'Salas del museo',
    room: 'Sala',
    roomHint: 'Elige un punto para ver sus elementos disponibles.',
    unavailable: 'El punto o elemento solicitado no está disponible.',
    mobile: 'En celular y tablet puedes explorar las salas y sus fichas en texto. La visita 3D requiere un computador con WebGL 2.',
    selection: 'Elementos de este punto',
    choose: 'Elegir elemento',
    openDetail: 'Abrir ficha completa',
    noSelection: 'Elige una pieza de este punto para consultar su ficha.',
    count: (count: number) => `${count} ${count === 1 ? 'elemento disponible' : 'elementos disponibles'}`,
    loading: 'Preparando recorrido…',
    controls: 'WASD o flechas: caminar · IJKL: mirar · Tab: puntos · Enter: activar · Esc: pausa. Para volver a los controles de la página, pulsa Esc y después Tab.',
    canvasLabel: 'Recorrido virtual. WASD o flechas para caminar; IJKL para mirar; Tab para puntos; Enter para activar; Escape para pausa y liberar el teclado.',
    textEyebrow: 'Experiencia / recorrido en texto',
    textTitle: 'Explora el museo',
    textIntro: 'Recorre las salas a tu ritmo y en el orden que prefieras. Las fichas ofrecen los textos y transcripciones disponibles.',
    controlsTitle: 'Controles del recorrido',
    roomNavigation: 'Salas del recorrido',
    noContent: 'No hay contenido disponible en este punto.',
    readNarration: 'Leer narración',
    top: 'Volver al comienzo',
  },
} as const
